accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article-list'),
    path('new/', views.ArticleCreateView.as_view(), name='article-create'),
    path('<str:pk>/', views.ArticleDetailView.as_view(), name='article-detail'),
    path('<str:pk>/edit/', views.ArticleUpdateView.as_view(), name='article-update'),
    path('<str:pk>/delete/', views.ArticleDeleteView.as_view(), name='article-delete'),


]

newspaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('articles/', include('articles.urls')),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)
    

articles/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article-detail', kwargs={'pk': self.pk})


class Comments(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.CharField(max_length=250)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if len(self.comment) > 50:
            return self.comment[:50] + '...'
        else:
            return self.comment

    def get_absolute_url(self):
        return reverse('article-list')

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'age')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'age')

articles/forms.py
from django.forms import ModelForm
from .models import Comments


class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ("comment", "author")

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .models import CustomUser
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import CustomUserCreationForm
# Create your views here.


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


def loginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = CustomUser.objects.get(username=username)
        except:
            messages.error(request, 'Wrong username or password')
        else:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('article-list')
            else:
                messages.error(request, 'Wrong username or password')
    return render(request, 'registration/login.html')


def logoutUser(request):
    logout(request)
    return redirect('article-list')

articles/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.detail import SingleObjectMixin
from django.urls import reverse_lazy, reverse
from django.shortcuts import render
from .forms import CommentForm
from django.views import View
from .models import Article


# Create your views here.


class ArticleListView(ListView):
    model = Article
    template_name = 'articles/article_list.html'


class CommentGet(DetailView):
    model = Article
    template_name = 'articles/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context


class CommentPost(SingleObjectMixin, FormView): # new
    model = Article
    form_class = CommentForm
    template_name = "article_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.article = self.object
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        article = self.get_object()
        return reverse("article_detail", kwargs={"pk": article.pk})


class ArticleDetailView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        view = CommentGet.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = 'articles/article_create.html'
    fields = ['title', 'body']
    success_url = reverse_lazy('article-list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    template_name = 'articles/article_update.html'
    fields = ['title', 'body']

    def test_func(self):
        article = self.get_object()
        return article.author == self.request.user


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    template_name = 'articles/article_delete.html'
    success_url = reverse_lazy('article-list')

    def test_func(self):
        article = self.get_object()
        return article.author == self.request.user

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.


class HomePageView(TemplateView):
    template_name = 'articles/article_list.html'

articles/templates/articles/article_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}New Article{% endblock title %}

{% block content %}

  <h1>New article</h1>
  <div>
    <form action="" method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
  </div>

{% endblock content %}

articles/templates/articles/article_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Delete Article{% endblock title %}

{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <h1>Delete {{ article.title }}</h1>
    <p>Are you sure you want to delete "{{ article.title }}"?</p>
    <button class="btn btn-danger ml-2" type="submit" value="Delete">Delete</button>
  </form>
{% endblock content %}

articles/templates/articles/article_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Article Detail{% endblock title %}

{% block content %}
  <div class="article-entry">
    <h2>{{ article.title }}</h2>
    <span>By {{ article.author }}  |  {{ article.date }}</span>
    <p>{{ article.body }}</p>
  </div>

  <h4>Add a comment</h4>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
  <button class="btn btn-success ml-2" type="submit">Save</button>
  </form>

  <hr>
    <h4>Comments</h4>
    {% for comment in article.comments_set.all %}
      <p>{{ comment.author }} &middot; {{ comment }}</p>
    {% endfor %}
  <hr>

    {% if request.user == article.author %}
    <p><a href="{% url 'article-update' pk=article.id %}">Update</a>  |
    <a href="{% url 'article-delete' pk=article.id %}">Delete</a></p>
  {% endif %}

{% endblock content %}

articles/templates/articles/article_list.html
{% extends 'base.html' %}
{% block title %}Articles{% endblock title %}

{% block content %}

{% for article in article_list %}
  <div class="card">
    <div class="card-header">
      <span class="font-weight-bold"><a href="{% url 'article-detail' pk=article.id %}">{{ article.title }}</a></span>
      <span class="text-muted">by {{ article.author|title }}  |
      {{ article.date }}</span>
    </div>

    <div class="card-body">
      <p>{{ article.body }}</p>
      {% if request.user == article.author %}
        <a href="{% url 'article-update' pk=article.id %}">Edit</a>  | <a href="{% url 'article-delete' pk=article.id %}">Delete</a>
      {% endif %}
    </div>

    <div class="card-footer">
      {% for comment in article.comments_set.all %}
        <p>
          <span class="font-weight-bold">
            {{ comment.author }} &middot;
          </span>
          {{ comment }}
        </p>
      {% endfor %}
    </div>
  </div>
  <br>
{% endfor %}
{% endblock content %}

articles/templates/articles/article_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Update Article{% endblock title %}

{% block content %}

  <h1>Update article</h1>
  <form action="" method="POST">
  {% csrf_token %}
  {{ form|crispy }}
    <button class="btn btn-info ml-2" type="submit">Update</button>
  </form>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}The Django Paper{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
<div class="container">
<header class="p-3 mb-3 border-bottom">
<div class="container">
<div class="d-flex flex-wrap align-items-center justify-content-center
justify-content-lg-start">
<a class="navbar-brand" href="{% url 'article-list' %}">Newspaper</a>
<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center
mb-md-0">
{% if user.is_authenticated %}
<li><a href="{% url 'article-create' %}" class="nav-link px-2 link-dark">+ New</a></li>
</ul>
<div class="dropdown text-end">
<a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
{{ user.username }}
</a>
<ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
<li><a class="dropdown-item" href="{% url 'password_change' %}">
Change password</a></li>
<li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
</ul>
  </div>
{% else %}

<div class="text-end">
<a href="{% url 'login' %}" class="btn btn-outline-primary me-2">
Log In</a>
<a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
</div>

{% endif %}
</div>
</div>
</header>
<main>
{% block content %}
{% endblock content %}
</main>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}
{% block content %}
  {% if user.is_authenticated %}
  <p>Hi, {{ user.username }}.</p>
  {% endif %}


{% endblock content %}